from multiprocessing import connection, Pipe
from threading import Thread
import tensorflow as tf
import numpy as np
from keras import backend as K
#heyo -from ali and rayyan
from yui_chess.config import Config
config = tf.compat.v1.ConfigProto(gpu_options = 
                         tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=0.8)
)
config.gpu_options.allow_growth = True
session = tf.compat.v1.Session(config=config)
tf.compat.v1.keras.backend.set_session(session)

class EngineInterface:
#Acts as a relay to return values generated by the policy and value networks
    def __init__(self, trained_model):  
        self.trained_model = trained_model
        self.pipes = []

    def start(self):
        prediction_worker = Thread(target=self._predict_batch_worker, name="prediction_worker")
        prediction_worker.daemon = True
        prediction_worker.start()

    def _predict_batch_worker(self):
        global graph
        graph = tf.get_default_graph()
        while True:
            ready = connection.wait(self.pipes,timeout=0.001)
            if not ready:
                continue
            data, result_pipes = [], []
            for pipe in ready:
                while pipe.poll():
                    data.append(pipe.recv())
                    result_pipes.append(pipe)

            data = np.asarray(data, dtype=np.float32)
            with graph.as_default():
                policy_ary, value_ary = self.trained_model.model.predict_on_batch(data)
            for pipe, p, v in zip(result_pipes, policy_ary, value_ary):
                pipe.send((p, float(v)))    

    def create_pipe(self):
        me, you = Pipe()
        self.pipes.append(me)
        return you



